### ISSUE TITLE
Poor text formatting in first time café dialogue.

### ISSUE THREAD

**Issue by TCAtrevor** [ShaffySwitcher/RhythmHeavenAdvance-armips#11]
Some conjoined words and a word broken between new lines are found in the dialogue given the first time you enter the café.

![image](https://github.com/ShaffySwitcher/RhythmHeavenAdvance/assets/16995298/4c66061e-507f-4148-8de1-271634082925)
![image](https://github.com/ShaffySwitcher/RhythmHeavenAdvance/assets/16995298/159db5c2-bd60-4bd4-87fe-b51cafb0c5d4)

**Comment by signalno11** [comment]
We'll look into the script files ASAP.

**Comment by TCAtrevor** [comment]
Yes, it looks like there are missing `[l` sequences that are used to signify line breaks.
https://github.com/ShaffySwitcher/RhythmHeavenAdvance/blob/807165fd1e65da4a789684777f9e667244dc8e59/src/script.txt#L9634-L9657

**Comment by TCAtrevor** [comment]
There seems to be no issue if I recompile with those `[l` sequences added! Someone might want to check if these sequences are missing anywhere else in the script.
![rh-eng-230610-203409](https://github.com/ShaffySwitcher/RhythmHeavenAdvance/assets/16995298/09a78298-e448-43a9-bc7e-5e5dc1f0eb12)
![rh-eng-230610-203418](https://github.com/ShaffySwitcher/RhythmHeavenAdvance/assets/16995298/5449c1e5-d254-42c3-9b4c-e624952d3e5b)

**Comment by signalno11** [comment]
Feel free to open a PR fixing the issue.
